apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web-server

spec:
  replicas: 2          # Tells Kubernetes to run 2 identical copies of this Pod
  selector:
    matchLabels:
      app: web-server  # Tells the Deployment which Pods belong to it

  template:
    metadata:
      labels:
        app: web-server # This label must match the selector above

    spec:
      containers:
      - name: nginx-container     ## node-app-container 
        image: nginx:1.26         ## technbd/node-app:latest
        ports:
        - containerPort: 80       ## port: 3000 
        resources: {} 

