apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
  
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    #nodePort: 30081

  selector:
    app: web-server
  type: ClusterIP     # NodePort or LoadBalancer

