apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    #nodePort: 30081

  selector:
    app: node-app
  type: ClusterIP     # NodePort or LoadBalancer

